### ISSUE TITLE
There are a couple of broken 'deploy to Vercel' button links in some readme files

### ISSUE THREAD

**Issue by diaz-camilo** [supabase/examples#39]
# Improve documentation

## Link 

* https://github.com/supabase/examples/tree/main/supabase-js-v1/todo-list/nextjs-todo-list/README.md
* https://github.com/supabase/examples/tree/main/supabase-js-v1/nextjs-with-supabase-auth/README.md
* https://github.com/supabase/examples/tree/main/supabase-js-v1/user-management/nextjs-ts-user-management/README.md

## Describe the problem

As the title says, There are a couple of broken 'deploy to Vercel' button links in some readme files.
When I tried to test some of the examples with Vercel by clicking the button it failed. Then, I figured out what had happened. the examples were migrated but their links were not updated.

## Describe the improvement

I've raised a PR for three of the buttons with updated links

## Additional context

After updating the links it now works for me.

**Comment by Isaiah-Hamilton** [comment]
Fixed https://github.com/supabase/examples/pull/38
